apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels: { app.kubernetes.io/name: {{ include "app.name" . }} }
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app.kubernetes.io/name: {{ include "app.name" . }} }
  template:
    metadata:
      labels: { app.kubernetes.io/name: {{ include "app.name" . }} }
    spec:
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
